### ISSUE TITLE
Plus7 addon Not working

### ISSUE THREAD

**Issue by Griffo** [xbmc-catchuptv-au/repo#29]
Hi,
I can't get Plus7 to work on 2 different Win10 machines. One is running Kodi 15.2, the other Kodi 16. All your addons  used to work fine.
The Kodi16 machine is a complete clean build from OS up. All your other plugins on this machine appear to work. 

In the cache folders mentioned below, there exists in each folder an m3u8 file and a bunch of key files. 

Kodi logs ->
17:39:03 T:6512  NOTICE: ADDONS: Using repository repository.xbmc.org
17:39:03 T:6512  NOTICE: ADDONS: Using repository repository.googlecode.xbmc-catchuptv-au
17:39:03 T:6512  NOTICE: Found screen: Generic PnP Monitor on AMD Radeon 6600M and 6700M Series, adapter 0.
17:39:03 T:6512  NOTICE: Primary mode: 1920x1080@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 800x480@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 960x540@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Additional mode: 1024x600@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1280x768@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1280x1024@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1400x1050@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1600x900@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1680x1050@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Previous line repeats 2 times.
17:39:03 T:6512  NOTICE: Additional mode: 1920x1080@ 60.00 - Full Screen
17:39:03 T:6512  NOTICE: Checking resolution 15
17:39:05 T:6512  NOTICE: Running database version Addons20
17:39:05 T:6512  NOTICE: Running database version ViewModes6
17:39:06 T:6512  NOTICE: Running database version Textures13
17:39:06 T:6512  NOTICE: Running database version MyMusic56
17:39:06 T:6512  NOTICE: Running database version MyVideos99
17:39:06 T:6512  NOTICE: Running database version TV29
17:39:06 T:6512  NOTICE: Running database version Epg11
17:39:06 T:6512 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
17:39:06 T:6512  NOTICE: ActiveAE DSP - starting
17:39:06 T:6512  NOTICE: initialize done
17:39:06 T:6512  NOTICE: Running the application...
17:39:07 T:6512  NOTICE: starting upnp client
17:39:07 T:1900  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
17:39:07 T:1900  NOTICE: UDP: Listening on port 9777
17:39:16 T:5648  NOTICE: Skin Helper Service --> skin helper service version 1.0.68 started
17:39:16 T:5648  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
17:39:36 T:6512  NOTICE: DVDPlayer: Opening: C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4333695411001\rendition.m3u8
17:39:36 T:6512 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:39:36 T:4744  NOTICE: Creating InputStream
17:39:36 T:4744  NOTICE: Creating Demuxer
17:39:37 T:4744   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4333695411001\rendition.m3u8
17:39:37 T:4744   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
17:39:37 T:4744  NOTICE: CDVDPlayer::OnExit()
17:39:37 T:6512  NOTICE: CDVDPlayer::CloseFile()
17:39:37 T:6512  NOTICE: DVDPlayer: waiting for threads to exit
17:39:37 T:6512  NOTICE: DVDPlayer: finished waiting
17:39:37 T:6512  NOTICE: CDVDPlayer::CloseFile()
17:39:37 T:6512  NOTICE: DVDPlayer: waiting for threads to exit
17:39:37 T:6512  NOTICE: DVDPlayer: finished waiting
17:39:58 T:6512  NOTICE: DVDPlayer: Opening: C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4652689744001\rendition.m3u8
17:39:58 T:6512 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:39:58 T:7292  NOTICE: Creating InputStream
17:39:58 T:7292  NOTICE: Creating Demuxer
17:40:00 T:7292   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4652689744001\rendition.m3u8
17:40:00 T:7292   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
17:40:00 T:7292  NOTICE: CDVDPlayer::OnExit()
17:40:00 T:6512  NOTICE: CDVDPlayer::CloseFile()
17:40:00 T:6512  NOTICE: DVDPlayer: waiting for threads to exit
17:40:00 T:6512  NOTICE: DVDPlayer: finished waiting
17:40:00 T:6512  NOTICE: CDVDPlayer::CloseFile()
17:40:00 T:6512  NOTICE: DVDPlayer: waiting for threads to exit
17:40:00 T:6512  NOTICE: DVDPlayer: finished waiting

**Comment by andybotting** [comment]
Can't check right now, but there is a setting in the add-on to use a
different streaming method.

Can you let me know what it is currently, and if it works if you change it?

Cheers
On 10 Apr 2016 6:13 PM, "Griffo" <notifications@github.com> wrote:

Hi,
I can't get Plus7 to work on 2 different Win10 machines. One is running
Kodi 15.2, the other Kodi 16. All your addons used to work fine.
The Kodi16 machine is a complete clean build from OS up. All other plugins
on this machine appear to work.

In the cache folders mentioned below, there exists in each folder an m3u8
file and a bunch of key files.

Kodi logs ->
17:39:03 T:6512 NOTICE: ADDONS: Using repository repository.xbmc.org
17:39:03 T:6512 NOTICE: ADDONS: Using repository
repository.googlecode.xbmc-catchuptv-au
17:39:03 T:6512 NOTICE: Found screen: Generic PnP Monitor on AMD Radeon
6600M and 6700M Series, adapter 0.
17:39:03 T:6512 NOTICE: Primary mode: 1920x1080@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 800x480@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 960x540@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Additional mode: 1024x600@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1280x768@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1280x1024@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1400x1050@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1600x900@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1680x1050@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Previous line repeats 2 times.
17:39:03 T:6512 NOTICE: Additional mode: 1920x1080@ 60.00 - Full Screen
17:39:03 T:6512 NOTICE: Checking resolution 15
17:39:05 T:6512 NOTICE: Running database version Addons20
17:39:05 T:6512 NOTICE: Running database version ViewModes6
17:39:06 T:6512 NOTICE: Running database version Textures13
17:39:06 T:6512 NOTICE: Running database version MyMusic56
17:39:06 T:6512 NOTICE: Running database version MyVideos99
17:39:06 T:6512 NOTICE: Running database version TV29
17:39:06 T:6512 NOTICE: Running database version Epg11
17:39:06 T:6512 WARNING: JSONRPC: Could not parse type
"Setting.Details.SettingList"
17:39:06 T:6512 NOTICE: ActiveAE DSP - starting
17:39:06 T:6512 NOTICE: initialize done
17:39:06 T:6512 NOTICE: Running the application...
17:39:07 T:6512 NOTICE: starting upnp client
17:39:07 T:1900 NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
17:39:07 T:1900 NOTICE: UDP: Listening on port 9777
17:39:16 T:5648 NOTICE: Skin Helper Service --> skin helper service version
1.0.68 started
17:39:16 T:5648 NOTICE: Skin Helper Service --> WebService - start helper
webservice on port 52307
17:39:36 T:6512 NOTICE: DVDPlayer: Opening:
C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4333695411001\rendition.m3u8
17:39:36 T:6512 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:39:36 T:4744 NOTICE: Creating InputStream
17:39:36 T:4744 NOTICE: Creating Demuxer
17:39:37 T:4744 ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file
C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4333695411001\rendition.m3u8
17:39:37 T:4744 ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
17:39:37 T:4744 NOTICE: CDVDPlayer::OnExit()
17:39:37 T:6512 NOTICE: CDVDPlayer::CloseFile()
17:39:37 T:6512 NOTICE: DVDPlayer: waiting for threads to exit
17:39:37 T:6512 NOTICE: DVDPlayer: finished waiting
17:39:37 T:6512 NOTICE: CDVDPlayer::CloseFile()
17:39:37 T:6512 NOTICE: DVDPlayer: waiting for threads to exit
17:39:37 T:6512 NOTICE: DVDPlayer: finished waiting
17:39:58 T:6512 NOTICE: DVDPlayer: Opening:
C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4652689744001\rendition.m3u8
17:39:58 T:6512 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:39:58 T:7292 NOTICE: Creating InputStream
17:39:58 T:7292 NOTICE: Creating Demuxer
17:40:00 T:7292 ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file
C:\Users\JohnGriffin\AppData\Roaming\Kodi\cache\plugin.video.plus7\brightcove_4652689744001\rendition.m3u8
17:40:00 T:7292 ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
17:40:00 T:7292 NOTICE: CDVDPlayer::OnExit()
17:40:00 T:6512 NOTICE: CDVDPlayer::CloseFile()
17:40:00 T:6512 NOTICE: DVDPlayer: waiting for threads to exit
17:40:00 T:6512 NOTICE: DVDPlayer: finished waiting
17:40:00 T:6512 NOTICE: CDVDPlayer::CloseFile()
17:40:00 T:6512 NOTICE: DVDPlayer: waiting for threads to exit
17:40:00 T:6512 NOTICE: DVDPlayer: finished waiting

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/xbmc-catchuptv-au/repo/issues/29>

**Comment by Griffo** [comment]
Well I feel a little silly. I had tried that option, but it seems it wasn't saving the setting. Something to do with the Titan skin and using a remote. So yes, that fixed it.
 
Thanks for the quick response, and sorry for wasting your time.

**Comment by andybotting** [comment]
Not a problem at all :)

Would have been nice to work out why the Compatibility mode didn't work for you though. Glad you're sorted out now though
